version: '3'
services:

    filebrowser:
        image: filebrowser/filebrowser:pi
        container_name: filebrowser
        restart: unless-stopped
        volumes:
           - /webdav:/srv 
           - $PWD/filebrowser.db:/database.db 
           - $PWD/filebrowser.json:/.filebrowser.json 
        networks:
            - web
        labels:
            - "traefik.backend=filebrowser"
            - "traefik.docker.network=web"
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.default.protocol=http"
            - "traefik.frontend.rule=Host:filebrowser.dominio.duckdns.org"
            - "traefik.frontend.headers.SSLHost=filebrowser.dominio.duckdns.org"
            - "traefik.frontend.headers.SSLRedirect=true"
            - "traefik.frontend.headers.SSLForceHost=true"

    webdav:
        container_name: webdav
        image: ugeek/webdav:arm
	      restart: unless-stopped
        volumes:
            - /webdav:/media
        environment:
            - USERNAME=usuario
            - PASSWORD=contraseña
            - UID=1000
            - GID=1000
            - TZ=Europe/Madrid
        networks:
            - web
        labels:
            - traefik.backend=webdav                                                                                               
            - traefik.frontend.rule=Host:webdav.dominio.duckdns.org
            - traefik.docker.network=web
            - traefik.port=80
            - traefik.enable=true
            # Adding in secure headers
            - traefik.http.middlewares.securedheaders.headers.forcestsheader=true
            - traefik.http.middlewares.securedheaders.headers.sslRedirect=true
            - traefik.http.middlewares.securedheaders.headers.STSPreload=true
            - traefik.http.middlewares.securedheaders.headers.ContentTypeNosniff=true
            - traefik.http.middlewares.securedheaders.headers.BrowserXssFilter=true
            - traefik.http.middlewares.securedheaders.headers.STSIncludeSubdomains=true
            - traefik.http.middlewares.securedheaders.headers.stsSeconds=63072000
            - traefik.http.middlewares.securedheaders.headers.frameDeny=true
            - traefik.http.middlewares.securedheaders.headers.browserXssFilter=true
            - traefik.http.middlewares.securedheaders.headers.contentTypeNosniff=tru
networks:                                                                                                                   
  web:
   external: true 
